# Generated by Django 5.1.1 on 2024-09-14 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Starter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startnumber', models.CharField(max_length=6)),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('lane', models.IntegerField(default=0)),
                ('state', models.IntegerField(choices=[(10, 'swimming'), (20, 'in'), (30, 'out'), (40, 'gone'), (50, 'done')], default='10', verbose_name='state')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logtimestamp', models.DateTimeField(auto_now_add=True, verbose_name='timestamp logged')),
                ('kind', models.IntegerField(choices=[(10, 'swimming'), (20, 'in'), (30, 'out'), (40, 'gone'), (50, 'done')], default='10', verbose_name='state')),
                ('starter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counter.starter')),
            ],
        ),
        migrations.CreateModel(
            name='LastLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counter.log')),
                ('starter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='counter.starter')),
            ],
        ),
    ]
